### ISSUE TITLE
Nested lists still not working.

### ISSUE THREAD

**Issue by magedhennawy** [dimpu/ngx-md#105]
I tried resolving it like the other issues have suggested, but it still doesn't seem to be working for me.

<img width="1537" alt="screen shot 2017-11-28 at 2 58 08 pm" src="https://user-images.githubusercontent.com/14252814/33341303-9804dc40-d44c-11e7-9428-b90ac71d31bc.png">

but when compiled and viewed.. 

![screen shot 2017-11-28 at 2 58 45 pm](https://user-images.githubusercontent.com/14252814/33341327-aa406cc6-d44c-11e7-9e11-9a275b3752eb.png)

This is included in my code, as it is in the demo.. 
<img width="1024" alt="screen shot 2017-11-28 at 2 59 07 pm" src="https://user-images.githubusercontent.com/14252814/33341366-c5c3c74a-d44c-11e7-8701-99d98ab876a8.png">

I would appreciate some help on how to get this up and running again

**Comment by zvonimirfras** [comment]
Same problem, are there any known workarounds?

**Comment by nextsoftpl** [comment]
+1

**Comment by nextsoftpl** [comment]
it works in https://github.com/jfcere/ngx-markdown

**Comment by dimpu** [comment]
This is working fine for me. 

Please check the demo
Following is a screenshot of the same demo.
![image](https://user-images.githubusercontent.com/1271995/34315727-499dcc9c-e752-11e7-934d-63bfb5ec41b5.png)

**Comment by lkduerig** [comment]
Checked the demo.
<img width="1403" alt="screenshot 2018-02-16 12 29 20" src="https://user-images.githubusercontent.com/2425822/36303572-3e21372a-1315-11e8-9871-3ab2da94cf76.png">

Is there a fix for this?
