### ISSUE TITLE
Question on plugin support

### ISSUE THREAD

**Issue by EdwinChua** [dimpu/ngx-md#113]
Is there a built in way to utilize the plugins here http://prismjs.com/download.html ? 

I tried downloading the prism.js file and including it, but for some reason, I'm getting `Uncaught TypeError: Illegal constructor`

Thanks for your time :)

**Comment by dimpu** [comment]
@EdwinChua We don't have any option to do that at this moment.

**Comment by EdwinChua** [comment]
Thanks, and apologies. I just realized that the prismjs library is completely separate from this one. Silly me...
