### ISSUE TITLE
&deg; not interpreted correctly as º

### ISSUE THREAD

**Issue by ds949** [dimpu/ngx-md#114]
360\&deg; when interpreted should show up as 360&deg; , but shows up as the original text

**Comment by dimpu** [comment]
@ds949 Could you please create a plunker.

**Comment by dimpu** [comment]
@ds949 I thinks something wrong with your app css. It's working fine for me. Please check it again.

![image](https://user-images.githubusercontent.com/1271995/34315660-f1a92faa-e750-11e7-9514-4688fffea7eb.png)

**Comment by dimpu** [comment]
Closing this issue. Feel free to re-open it if your issue still not resolve.
