### ISSUE TITLE
Move package to ngx-md.

### ISSUE THREAD

**Issue by dimpu** [dimpu/ngx-md#115]
Ok. angular2-markdown created when angular was in beta stage. Since then there are so many updates to the packages. 

In https://github.com/dimpu/angular2-markdown/issues/93 issue  @mischkl sugged to use ngx-* for the package name. I really think that's a great idea.

So, I'm thinking of moving to `ngx-md` module. What do you guys think?

**Comment by NikoRoberts** [comment]
👍
