### ISSUE TITLE
Tables and Blockquotes not formatted as in sample

### ISSUE THREAD

**Issue by joerglang** [dimpu/ngx-md#118]
Installed version 3.1.0 in an Angular 5 application. For testing I added the same markup as provided in https://dimpu.github.io/ngx-md/ in my test file.

Most of it looks ok, but tables and the blockquotes are not formatted as in the online sample, even though the markup is the same. (Copy & Paste). 
When looking at the generated html code I see that your sample adds additional classes. My html does not contain those classes. (Tables have class="table2" added). 

Is this a known issue?
Or am I missing something?

**Comment by dimpu** [comment]
I'm not very sure what's happening with your application. But it's working fine. For me. Could u share a plunker link please?

**Comment by joerglang** [comment]
I quite busy right now, but I try to strip down my solution and share it with you. Not sure if it will be plunker as I haven't created a solution there yet and time is sparse. But you will hear from me...

**Comment by joerglang** [comment]
Hi Dimpu

I stripped down my solution to show the effect.
After npm install and npm start you should see the effect.


Regards
Jörg

Von: Dimpu Aravind Buddha [mailto:notifications@github.com]
Gesendet: Freitag, 29. Dezember 2017 00:55
An: dimpu/ngx-md <ngx-md@noreply.github.com>
Cc: Jörg Lang <jlang@evelix.ch>; Author <author@noreply.github.com>
Betreff: Re: [dimpu/ngx-md] Tables and Blockquotes not formatted as in sample (#118)


I'm not very sure what's happening with your application. But it's working fine. For me. Could u share a plunker link please?

**Comment by eltrhn** [comment]
Confirming. Nested lists also do not function properly, appearing on the same level as what should be their containing list. It would appear that the version available through npm / on GitHub isn't the same one running in the live demo...?

Here is a plunker: https://embed.plnkr.co/RUHPRiQ5IwmfndwYSJjz/

And as shown [here](https://embed.plnkr.co/GRDnauwKW39fF2nUntAi/), the issues with CSS styling can be solved with liberal application of `::ng-deep` in CSS styling (note that I've tweaked some of the fonts/styles, so it's not a perfect match to the live demo)... but this of course does nothing to solve the issue with sub-lists.
