### ISSUE TITLE
Nested list does't work when directly write at .md file or in <mardown><mardown> html

### ISSUE THREAD

**Issue by StartE** [dimpu/ngx-md#121]
when I write 
* 111
* 1111
    * 222
    * 2222
it will transfor into 
 &lt;ul>
    &lt;li>111 &lt;/li>
    &lt;li>1111 &lt;/li>
    &lt;li>222 &lt;/li>
     &lt;li>2222 &lt;/li>
 &lt;ul>
**not**
 &lt;ul>
    &lt;li>111 &lt;/li>
    &lt;li>1111 &lt;/li>
     &lt;li> &lt;ul>
            &lt;li>222 &lt;/li>
            &lt;li>2222 &lt;/li>
            &lt;/ul> &lt;li>
 &lt;ul>
both Nested list write in md file or in directly html with <markdown> <markdown> tag
it only works when &lt;markdown [data] = "markdownData"> &lt;/markdown>

**Comment by lkduerig** [comment]
I'm having the same problem, using Contentful's markdown editor. I've checked the data coming through the API and there is nothing wrong with the formatting there, so this seems to be a more general problem with how it is parsed. Nested lists get flattened, no matter how the markdown is written or where it comes from.

**Comment by lkduerig** [comment]
Running the demo, I get this: 
<img width="1403" alt="screenshot 2018-02-16 12 29 20" src="https://user-images.githubusercontent.com/2425822/36303548-279902ee-1315-11e8-921e-6f42bd58a74e.png">

**Comment by mfonolleda** [comment]
Same here...

**Comment by thendarion** [comment]
there's this function in markdown.component.ts called prepare which trims lines. but this butchers lists because lists depend on leading spaces. why does this function even exist here?

**Comment by dimpu** [comment]
Please try latest version

**Comment by Jonathan002** [comment]
> Please try latest version

I'm using the latest version and this still appears to be the case for me with the path input property.

```
  <markdown path="/assets/md/my-markdown-file.md"></markdown>
```
