### ISSUE TITLE
Lazy modules and interceptor

### ISSUE THREAD

**Issue by Dockdep** [dimpu/ngx-md#124]
Hello, I have some problems in my project with ngx-md. I use it in lazy module, and when I imported it, all http interceptors what was included in this module from parents modules stop working, when I inject interceptors in lazy module directly everything goes fine. Any ideas?

**Comment by bassoGeorge** [comment]
I'm facing the exact same issue. All interceptors from parent modules stop working. It's like the forRoot() is wiping off the interceptor list. Makes this tool pretty much unusable for me...

**Comment by bassoGeorge** [comment]
Yes, I'm sure it is the export of CommonModule and HttpClientModule. Lazy modules get their own injector I believe and exporting HttpClient from MarkdownModule will overwrite the HttpClient from parent module..

Why are we exporting CommonModule and HttpClientModule? Doesn't make sense... Let me try it out and maybe go for a PR

**Comment by bassoGeorge** [comment]
Okay, so apparently this is a known issue with HttpClientModule. You should only import it once in a project. Importing it within a lazy module or dependency of a lazy module plays havoc with HTTP_INTERCEPTORS token. The correct solution would be to import CommonModule and HttpClientModule *only if it is not already imported*. How to do that might be tricky. In the meanwhile, I'll just fork this and remove the imports and exports of these modules. Works in that situation

**Comment by ghtjiann4321** [comment]
Any updates on this? Interceptors stopped working after using this module

**Comment by thiagoburgo** [comment]
Same problem here!

@bassoGeorge your fork work as expected? 


Tkns

**Comment by jaysalvat** [comment]
Hello.

+1 same problem here.

There is only a MarkdownModule.forRoot() way to import the module and no MarkdownModule.forChild().

Some help?
http://weblogs.thinktecture.com/thomas/2017/05/the-real-secrets-behind-forroot-andor-forchild-of-an-ngmodule.html

**Comment by sroettering** [comment]
is there any update/progress on this issue? we use this module in an enterprise application with a lot of lazy loaded modules. it was pretty annoying to debug why our interceptors stopped working.

**Comment by nieschl** [comment]
Please remove all HttpClientModule imports in this package.

**Comment by dimpu** [comment]
resolved.
