### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by rjrudman** [dimpu/ngx-md#129]
Links should be validated before being rendered.

One could write:

`[Click Me](javascript:alert('Injected!'%29)`

Which renders a 'Click Me' link, which can run arbitrary javascript.

In comparison, here's how GitHub handles it:

1. Escaped closing parens (Fails to render)

[Click Me](javascript:alert('Injected!'%29)

2. Non-escaped closing parens (Strips link)

[Click Me](javascript:alert('Injected!'))

**Comment by danielsogl** [comment]
@rjrudman Hold my beer!
