### ISSUE TITLE
Nested Lists not working.

### ISSUE THREAD

**Issue by lkduerig** [dimpu/ngx-md#130]
I tried the demo.

https://user-images.githubusercontent.com/2425822/36303572-3e21372a-1315-11e8-9871-3ab2da94cf76.png

Will there be a fix for this?

**Comment by dimpu** [comment]
I don't see any issue with my demo. Please check it here.
https://dimpu.github.io/ngx-md/

![image](https://user-images.githubusercontent.com/1271995/36412347-dd3b7968-15e7-11e8-86ec-68395b7cadda.png)

**Comment by lkduerig** [comment]
I think I found my problem with this. I didn't realize that we were using a customized version of this module temporarily to address the XSS vulnerability issue until there was a fix for that one. So we are not getting updates to the code. 

Thanks for taking the time to answer.

**Comment by lkduerig** [comment]
I tried the demo locally as the project page suggested, and the nested lists aren't actually working there, either? They work on the demo page you linked to, but not locally at all.

**Comment by lkduerig** [comment]
The issue is coming from around line 120 of markdown/markdown.component.js. This block of code which seems to solve an edge case is stripping out the spaces needed to format the list items.

**Comment by Olli-palkkaus** [comment]
I confirm that the bug is in line 112 of `markdown/markdown.component.ts`: 

```
if (this._ext === 'md' || !this.path) {
            let isCodeBlock = false;
            return raw.split('\n').map((line: string) => {
                if (this.trimLeft(line).substring(0, 3) === "```") {
                    isCodeBlock = !isCodeBlock;
                }
                return isCodeBlock ? line : line.trim();
            }).join('\n');
        }
```

Commenting out `return isCodeBlock ? line : line.trim();` to `return line;` fixes the issue.

Looking at it, I am not quite sure how this can work in other environments. It will obviously strip any leading spaces in the beginning of the line as as such remove nesting in lists.

**Comment by lkduerig** [comment]
I tried commenting out the block, but it caused other problems. When it didn't strip out spaces, leading spaces were left in places where they didn't belong elsewhere. This block of code is executed to prepare any or all elements, not only lists. I used patch-package to generate this diff to fix the issue and include the patch in the build process:

`patch-package
--- a/node_modules/ngx-md/markdown/markdown.component.js
+++ b/node_modules/ngx-md/markdown/markdown.component.js
@@ -119,13 +119,15 @@ var MarkdownComponent = (function () {
         }
         if (this._ext === "md" || !this.path) {
             var isCodeBlock_1 = false;
+            var isListItem_1 = false;
             return raw
                 .split("\n")
                 .map(function (line) {
                 if (_this.trimLeft(line).substring(0, 3) === "```") {
                     isCodeBlock_1 = !isCodeBlock_1;
                 }
-                return isCodeBlock_1 ? line : line.trim();
+                isListItem_1 = /^( *)((?:[*+-]|\d+\.)) [^\n]*(?:\n(?!\1(?:[*+-]|\d+\.) )[^\n]*)*/gm.test(line);
+                return isCodeBlock_1 || isListItem_1 ? line : line.trim();
             })
                 .join("\n");
         }
`

End result:

`    MarkdownComponent.prototype.prepare = /**
       * Prepare string
       */
    function (raw) {
        var _this = this;
        if (!raw) {
            return "";
        }
        if (this._ext === "md" || !this.path) {
            var isCodeBlock_1 = false;
            var isListItem_1 = false;
            return raw
                .split("\n")
                .map(function (line) {
                if (_this.trimLeft(line).substring(0, 3) === "```") {
                    isCodeBlock_1 = !isCodeBlock_1;
                }
                isListItem_1 = /^( *)((?:[*+-]|\d+\.)) [^\n]*(?:\n(?!\1(?:[*+-]|\d+\.) )[^\n]*)*/gm.test(line);
                return isCodeBlock_1 || isListItem_1 ? line : line.trim();
            })
                .join("\n");
        }
        return raw.replace(/\"/g, "'");
    };
`
Not ideal, the regex there is what Marked library uses to identify list items. But in case it helps anyone else...

**Comment by dimpu** [comment]
@lkduerig If the issue resolved could you please close this.

**Comment by djtahl** [comment]
I think the issue has been identified but not implemented in ngx-md package that's why the issue can't be considered as fixed.
I just added the package in my dependencies and the nested list are still not working.

**Comment by GerkinDev** [comment]
@lkduerig which issues do you encounter by simply skipping the whole non-codeblock trim? I've tried it and it seems to work....

**Comment by Olli-palkkaus** [comment]
I would also give my vote to skipping the whole trim. Trimming will hurt many other features than just nested lists. At least BR in markdown is two spaces at the end of line and I think there are other commonly used scenarios.

Probably (this is just a guess) the problems would occur if the markdown is intended with HTML. e.g.

```
<html>
    <body>
        <ngx-md>
            ### your markdown code

            second line
        </ngx-md>
    </body>
</html>
```

If you do not do the trim, 4 spaces indent becomes code block / pre, so you would need to write it like this:

```
<html>
    <body>
        <ngx-md>
### your markdown code

second line
        </ngx-md>
    </body>
</html>
```

For us, this restriction was fine and that's why I made the change to my version. But I did not make a pull request because I was afraid I would mess someone else's existing HTML. 

Probably the perfect solution would be:

- Trim empty **lines** from the beginning
- Take the first line where there is text
- Check how many spaces are in the first line before text
- Trim all the lines with this amount of spaces.
  - Only take away spaces, not other characters.

**Comment by GerkinDev** [comment]
> Probably (this is just a guess) the problems would occur if the markdown is intended with HTML

In this case, the `trimLeft` should be applied only on transcluded content, not document nor markdown from a var or a string.

> * Check how many spaces are in the first line before text
> * Trim all the lines with this amount of spaces.
>     * Only take away spaces, not other characters.

All blank characters should be taken, not just spaces. Think about tab-indented HTML docs.
I'd rather think about removing *at most* the same number of blanks than on the first text-containing line. It would allow using blank lines, with or without keeping the indent

**Comment by GerkinDev** [comment]
Without answer from @lkduerig to give me informations about the problem encountered without trim, I can't do a PR right now. Anyway, I've planned to do it asap.

Meanwhile, I personnaly switched to [ngx-showdown](https://github.com/yisraelx/ngx-showdown), almost equivalent. Both [marked](https://github.com/markedjs/marked) & [showdown](https://github.com/showdownjs/showdown) have minimal maintenance, so there's no big difference between them. And nested lists works out of the box with the current version.
