### ISSUE TITLE
ionic shared MarkdownService

### ISSUE THREAD

**Issue by Eraldo** [dimpu/ngx-md#133]
Currently I am doing this in every component where I want to use the markdown component:
```ts
constructor(private markdownService: MarkdownService) {
    this.markdownService.setMarkedOptions({gfm: true, breaks: true})
}
```
I am using ionic 3 with lazy loading and it seems every time I import the MarkdownModule into a component it creates a new instance of MarkdownService -- which is not what I want.
Related issue: https://github.com/dimpu/ngx-md/issues/65

How can I share these settings across my components? (i.e. define it only once)
Assistance appreciated. :)

**Comment by dimpu** [comment]
Could you try to install the latest version and check again, please.
