### ISSUE TITLE
Angular 6 Compability

### ISSUE THREAD

**Issue by Flo9818** [dimpu/ngx-md#135]
### Improvement
Because Angular 6 will be using RXJS 6, but ngx-md is still using 5.5.
### TODO
Upgrade RXJS to version 6

**Comment by muuvmuuv** [comment]
Is there any workaround? I really want to update to 6, but `ng update @angular/core` fails with:

```
Package "angular2-markdown" has an incompatible peer dependency to "rxjs" (requires "^5.5.2", would install "6.1.0").
Invalid range: "*"
```

**Comment by christianrondeau** [comment]
In the meantime, you can install `npm i rxjs-compat` and ignore the warning (e.g. temporarily remove it from `package.json` and add it again) - this allows rxjs backward compatibility.

**Comment by roeb** [comment]
We're waiting for it, too. Any news yet? npm i `rxjs-compat` is not really a long-term solution ;)

**Comment by dimpu** [comment]
Now we support Angular 6. From now our package will be in sync with the angular major release install `npm i ngx-md@lates --save`  for ngx-md 6.0.0
