### ISSUE TITLE
forRoot() yields "function calls are not supported in decorators but 'NgxMdModule' was called." error

### ISSUE THREAD

**Issue by rtm** [dimpu/ngx-md#139]
Thanks for putting out the Angular 6 version, but when I do the following in my module:

    imports: [NgxMdModule.forRoot()]

When building for production, I get

> Function calls are not supported in decorators but 'NgxMdModule' was called.

**Comment by dimpu** [comment]
@rtm. I'm not able to reproduce that issue. Let's see if anyone else have the same issue.

**Comment by rtm** [comment]
@dimpu Thanks for checking. I don't know stackblitz that well--is this example running `--aot`, which is apparently what causes the problem in my case?

**Comment by rtm** [comment]
Please take a look at https://github.com/rtm/ngx-md-compile-problem.

**Comment by dimpu** [comment]
resolved.
