### ISSUE TITLE
open links in new tab

### ISSUE THREAD

**Issue by hjjobs** [dimpu/ngx-md#141]
When embedding a link using markdown it opens in the same tab. Is there any way through which we can open the link in a new tab ?

**Comment by dimpu** [comment]
use <a href="http://example.com/" target="_blank">Hello, world!</a>

**Comment by lwator** [comment]
> What should I use?
use [Hello, world!](http://example.com/)

**Comment by timvl** [comment]
Hi, is it possible to configure that links will be opened in a new window (target="_blank")?
