### ISSUE TITLE
Feature onLoad @output

### ISSUE THREAD

**Issue by wkjesus** [dimpu/ngx-md#143]
it would be nice if the componente implement an onload to know when file loaded, to call other functionlity based on this one. Thx.

**Comment by dimpu** [comment]
resolved

**Comment by maheswar** [comment]
Thanks for the fix.But this functionality not working. Will post some example how to use it.

I tried following example.

https://www.npmjs.com/package/ngx-md

<div NgxMd [path]="'/path/to/readme.md'" (error)="errorHandler($event)" (loaded)="loadedHandler($event)" (onLoad)="loaded($event)"></div>

But the above code not triggering any method.Please look into this.

**Comment by dimpu** [comment]
@maheswar I just published a new version to npm. Could you please try it again.

**Comment by dimpu** [comment]
@maheswar It's working for me.

Please check this example https://stackblitz.com/edit/ngx-md-exmaple?file=src%2Fapp%2Fapp.component.html

**Comment by maheswar** [comment]
@dimpu thanks  for the example link.
In my project 
`npm install ngx-md --save`
 not installing latest , i see it's 6.0.9
Thanks for the link , In link it is working fine(but firing twice).

Just a suggestion : It would be great if we support for page navigation(anchor scrolling).

**Comment by maheswar** [comment]
@dimpu thanks for the support.
But the `**loaded()**` is called before it loads to the dom.

I need a event once the dom is ready with md file.

Please look into this.
