### ISSUE TITLE
Setting data to or blank string is a no-op

### ISSUE THREAD

**Issue by rtm** [dimpu/ngx-md#145]
I'm puzzled by the following code:

```
@Input()
    set data(value: string) {
      if (value) {
        this._data = value;
        this.onDataChange(value);
      }
    }
```

The `if (value)` means that if `data` is ever changed to null or the empty string, it is ignored. What is the intent of that logic?

The previous version did not work like that.

**Comment by dimpu** [comment]
Old issue.

**Comment by rtm** [comment]
> Old issue.

Thanks for answering, but please help me out here since my app doesn't work in the way that I would expect. Is the issue old in the sense of used to exist but was resolved, or in the sense of was raised and it was explained why it worked that way, or...?
