### ISSUE TITLE
Set renderer type

### ISSUE THREAD

**Issue by szechyjs** [dimpu/ngx-md#148]
Currently NgxMdService.renderer has type of `any`. This should be changed to the `Renderer` type imported from `marked`.

https://github.com/dimpu/ngx-md/blob/master/src/markdown/markdown.service.ts#L8

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/marked/index.d.ts#L69

**Comment by dimpu** [comment]
@szechyjs Could you create a PR please?

**Comment by dimpu** [comment]
Done
