### ISSUE TITLE
The HTML are translated into Unicode when rendering

### ISSUE THREAD

**Issue by Adonais0** [dimpu/ngx-md#150]
It works well with other languages, except for HTML. I used the default settings. See screenshot below:
![screen shot 2018-08-22 at 09 52 05](https://user-images.githubusercontent.com/31697300/44450448-3c2bb980-a5f1-11e8-9278-8c5584d8697d.png)

**Comment by MSakamaki** [comment]
I got a similar phenomenon, but I solved it by data binding.

`text = '<h1>H1 TITLE</h1>'`

### Serialized

```html
<ngx-md>{{ text }}</ngx-md>
```

### Not serialized

```html
<ngx-md [data]="text"></ngx-md>
```
