### ISSUE TITLE
Can't resolve '../../../../../node_modules/ngx-md/ngx-md.ngfactory'

### ISSUE THREAD

**Issue by rtm** [dimpu/ngx-md#151]
I am using v6.0.0 alongside Angular 6.x versions, and now am getting the following on production builds:

```
ERROR in ./src/app/pods/dashboard/dashboard-table/dashboard-table.component.ngfactory.js
Module not found: Error: Can't resolve '../../../../../node_modules/ngx-md/ngx-md.ngfactory' in '/home/rtm/repos/nims/red/console/src/app/pods/dashboard/dashboard-table'
ERROR in ./src/app/pods/visual-report/unit-results/unit-results.component.ngfactory.js
Module not found: Error: Can't resolve '../../../../../node_modules/ngx-md/ngx-md.ngfactory' in '/home/rtm/repos/nims/red/console/src/app/pods/visual-report/unit-results'
```

Although my memory is hazy, I seem to recall similar problems in the past. If all else fails, I will try to create a repro case and/or start trying to isolate this, but in the meantime does anyone have any ideas about possible causes?

This might, or might not, be related to `@angular/compiler[-cli]@1.6.3`? See https://github.com/angular/angular/issues/25424.

**Comment by dimpu** [comment]
Closing since it's related to https://github.com/angular/angular/issues/25424
