### ISSUE TITLE
Cleanup projects

### ISSUE THREAD

**Issue by GerkinDev** [dimpu/ngx-md#152]
Hi there!

I'm currently building a website using user-generated markdown documents. But I encounter 2 known issues (#129 & #130).

* [x] About the XSS vulnerability, I'd like to use the [DomSanitizer's `sanitize` method](https://angular.io/api/platform-browser/DomSanitizer#sanitize) as opposed to #132.
* [x] For the nested list issues, I've not yet done experimentations, but I have read the whole thread of #130 and I'll start with the user suggestions.

I would be really happy to help and send you a lil' PR (with *unit tests* of course), but I don't understand why you have 2 projects.

For what I understand, the module published on npm is in either `projects/ngx-md` or `projects/ngx-md2`. But what is the difference between both projects? Why none of the `package.json` version field is at *6.0.0*?

Cheers!

---

Footnote: I'm uses to develop non-angular libs, sorry for my misunderstanding of a part of the project. [This article](https://blog.angularindepth.com/creating-a-library-in-angular-6-87799552e7e5) gave me the kick in my ass I needed

**Comment by dimpu** [comment]
HI @GerkinDev. I have refactored the code base.

1) upgrade angular v6
2) Use Angular library feature to publish to npm.
3) some code clean up.

I pushed  `projects/ngx-md2` by mistake. Now it's resolved.
