### ISSUE TITLE
How to custom css for code?

### ISSUE THREAD

**Issue by Eve-1995** [dimpu/ngx-md#168]
I'm sorry to disturb u.
My `ngx-md` performs like below
![12](https://user-images.githubusercontent.com/30228406/52901347-85c22d80-323d-11e9-8354-78a85d27d903.png)
The part of code is not clear. I wanna set the color of text as white, and I tried.

      ngx-md {
            code {
                display: none;
                color: white !important;
            }
        }
But it didn't works.  Can u just tell me what to do?

**Comment by Eve-1995** [comment]
I have solved this problem via `::ng-deep`

**Comment by FOSSforlife** [comment]
I've heard that `::ng-deep` will be deprecated. Is there any long-term solution for this?

**Comment by dimpu** [comment]
You can use CSS with `!important`.
