### ISSUE TITLE
Compatibility for Angular 10

### ISSUE THREAD

**Issue by thomas3577** [dimpu/ngx-md#193]
This package does not seem to be compatible with Angular 10. When I try to upgrade my Angular app (`ng update --all`), I get the following error message:

`Package "ngx-md" has an incompatible peer dependency to "@angular/common" (requires "^8.0.0" (extended), would install "10.0.1").
                  Package "ngx-md" has an incompatible peer dependency to "@angular/core" (requires "^8.0.0" (extended), would install "10.0.1").
× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "C:\Users\lalala\AppData\Local\Temp\ng-JW7sIB\angular-errors.log" for further details.`

**Comment by dimpu** [comment]
Updated to angular 12
