### ISSUE TITLE
there is no NgxMdModule exported in version 12.0.0

### ISSUE THREAD

**Issue by saherelm** [dimpu/ngx-md#215]
when install v12.0.0 there is no module exported.
i think you publish wrong content to package.

regards

**Comment by NicolasPerr** [comment]
UP!  I confirm no module exported.

**Comment by dimpu** [comment]
published it again.

**Comment by saherelm** [comment]
tnx ...
    Hadi Khazaee AslMaster Of Science in Information Technology E-Commerce SubField
***@***.*** 

    On Wednesday, August 4, 2021, 01:15:18 AM GMT+4:30, Dimpu Aravind Buddha ***@***.***> wrote:  
 
 


published it again.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ncrawlins** [comment]
still won't build in my angular project.
Error: The target entry-point "ngx-md" has missing dependencies:
 - he

**Comment by RaghavendhraK** [comment]
Just for the info. PeerDependencies still pointing to Angular version < 10 in ngx-md Version 12.0.5
"peerDependencies": {
    "@angular/common": ">= 8.0.0 < 10.0.0",
    "@angular/core": ">= 8.0.0 < 10.0.0"
  }
  
Thanks,
Raghu

**Comment by mac-bhaird** [comment]
Getting a peerDependency message as per @ncrawlins and build error as per @RobinKamps

**Comment by ncrawlins** [comment]
> > still won't build in my angular project.
> > Error: The target entry-point "ngx-md" has missing dependencies:
> > 
> > * he
> 
> try:
> 
> `npm install he`
If that's how it's meant to be handled then he should be set as a peer dependency, but I don't think it really qualifies as a peer dependency.  It should just get installed if I install ngx-md.  Like angular depends on the "magic-string" package for example but I don't have to manually install that.   there is something messed up in the ngx-md package configuration.

**Comment by cjam** [comment]
> > > still won't build in my angular project.
> > > Error: The target entry-point "ngx-md" has missing dependencies:
> > > 
> > > * he
> > 
> > 
> > try:
> > `npm install he`
> 
> If that's how it's meant to be handled then he should be set as a peer dependency, but I don't think it really qualifies as a peer dependency. It should just get installed if I install ngx-md. Like angular depends on the "magic-string" package for example but I don't have to manually install that. there is something messed up in the ngx-md package configuration.

It's strange that `he` is clearly in the dependencies of this package, and yet don't show up in the published package.json (see dependencies [here](https://www.npmjs.com/package/ngx-md?activeTab=dependencies)) and therefore isn't installed.  Perhaps an issue with the auto publish that was added recently? 

Here's a screen shot of the `package.json` of this package in my `node_modules` 
![image](https://user-images.githubusercontent.com/1000288/133486500-00088c9c-1caa-44f2-b5b9-451a734d0b84.png)

**Comment by joebnc** [comment]
> Just for the info. PeerDependencies still pointing to Angular version < 10 in ngx-md Version 12.0.5
> "peerDependencies": {
> "@angular/common": ">= 8.0.0 < 10.0.0",
> "@angular/core": ">= 8.0.0 < 10.0.0"
> }
> 
> Thanks,
> Raghu

Was this resolved yet?
Thanks.

**Comment by seidnerj** [comment]
This is still an issue, can't install with Angular 12.

**Comment by hampton1122** [comment]
This is still an issue. Any idea when it will be fixed?
