### ISSUE TITLE
Question about dynamic elements

### ISSUE THREAD

**Issue by pnowy** [dimpu/ngx-md#80]
Hi,

I'm struggling with the markdown and angular2 links/hrefs. I need the relative links within my MD documentation between the specific pages. 

Let's assume that I have page doc1.md and doc2.md. I want to have on the page doc1.md link to page doc2.md but I would like to serve it and render by single component (which is of course part of entire page which has navbar, etc. - just normal case).

Because I cannot use just links but I have to replace the displayed content for the component which render my docs I was thinking about MarkdownService.renderer.link customization. Something like that:

```
this._markdown.renderer.link = (href: string, title: string, text: string) => {
      return '<a (click)="changePath(\''+href+'\')" title="' + title + '" >' + text + '</a>';
};
```
And the path would be replaced by rendering component, something like that:

```
<div Markdown path="{{markdownPath}}"></div>
```

Unfortunately when I prepare custom render angular doesn't recognize the link click on given `a` element. Do you know or could give a hint is it possible to deal with the problem by angular2-markdown - I don't know some kind of dynamic generation or something like that?

Thanks for any advice.

BR

**Comment by figuerres** [comment]
sounds like an item i am thinking about right now.
i am thinking of making a "wiki" in angular x  with this package and i think i have an idea of what needs to happen.

the answer has a lot to do with routing ....

so part of the thing is we need to make a route that has optional child routes that map to the component / view.

possibly inject routing table entries into the angular routing table (may not be needed)
possibly make the links that are "app relative" become angular router link items, that would cause the angular runtime to call the router to do the Navigation for us.

look here [https://angular.io/tutorial/toh-pt5](url)

and at the section on router links and dynamic router links

**Comment by figuerres** [comment]
this might work, use dynamic component module along with the router link tag..... when the link is in the angualr app and not a link to another web site

[https://stackoverflow.com/questions/42123385/angular2-dynamic-html-with-functional-routerlink](https://stackoverflow.com/questions/42123385/angular2-dynamic-html-with-functional-routerlink)

**Comment by pnowy** [comment]
I've used the following approach: https://plnkr.co/edit/mcvILwmOLvrS2PxIrXX8?p=preview
